spring:
  application:
    name: mesh-service

server:
  port: 0
  ssl:
    enabled: true
    key-store: classpath:client-keystore.jks
    key-store-password: 123456
    key-alias: client-app
    key-store-type: PKCS12
    trust-store: classpath:client-truststore.jks
    trust-store-password: 123456
    trust-store-type: JKS
    client-auth: want

logging:
  file:
    name: logs/mesh-service.log

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    non-secure-port-enabled: false   # Disable non-secure HTTP port
    secure-port-enabled: true        # Enable secure HTTPS port
    secure-port: ${server.port}