spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  redis:
    host: ${REDIS_GATEWAY_URL:localhost}
    port: 6379
  session:
    store-type: none #
  security:
    oauth2:
      client:
        registration:
          lite-mesh-gateway-client:
            client-id: lite-mesh-gateway-client
            client-secret: SVwQlpupiIKUctK1Vh0yYwLxgkMZjjqY
            authorization-grant-type: client_credentials
            scope: gateway.read
            provider: keycloak  # identity-provider
        provider:
          keycloak:
            token-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh/protocol/openid-connect/token
            authorization-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh/protocol/openid-connect/auth
            jwk-set-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh/protocol/openid-connect/certs
            issuer-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh
      resourceserver:
        opaquetoken:
          introspection-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh/protocol/openid-connect/token/introspect
          client-id: lite-mesh-gateway-client
          client-secret: SVwQlpupiIKUctK1Vh0yYwLxgkMZjjqY
        jwt:
          issuer-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh
          jwk-set-uri: http://${KEYCLOAK_GATEWAY_URL:localhost}:${KEYCLOAK_GATEWAY_PORT:8281}/realms/LiteMesh/protocol/openid-connect/certs
  data:
    mongodb:
      uri:  mongodb://root:mongopw@${MONGO_GATEWAY_URL:localhost}
      database: LiteMesh
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true #enable the Resilience4J auto-configuration
    loadbalancer:
      enabled: true # Enable Spring Cloud LoadBalancer for service-to-service discovery
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
#        http2: false  # Explicitly disable HTTP/2 on the gateway
#        sslHandshakeTimeout: 30s  # Increase SSL handshake timeout if needed
#      loadbalancer:
#        use404: true
#      forward-routing:
#        enabled: false

      discovery:
        locator:
          enabled: true # Enables service discovery with Eureka
          lower-case-service-id: true  # This ensures service IDs are matched in lowercase
      routes:
        ## Discover server route
        # so, our gateway port is 7777, we access the discovery server through http://localhost:7777/eureka/web
        # the filter is to reroute the request from http://localhost:7777/eureka/web to http://localhost:8761
      - id: discovery-server
        uri: https://${EUREKA_GATEWAY_URL:localhost}:8761
        predicates:
        - Path=/eureka/web
        filters:
          - SetPath=/

        ## Discovery server static resources
      - id: discovery-server-static
        uri: https://${EUREKA_GATEWAY_URL:localhost}:8761
        predicates:
        - Path=/eureka/**

        ## Mesh Service (Main Web User Interface)
      - id: mesh-service
        uri: lb://mesh-service
        predicates:
        - Path=/mesh/**

#        ## Inventory Service (Just to Test) (This is being loaded dynamically from mongodb)
#      - id: inventory-service
#        uri: lb://inventory-service
#        predicates:
#        - Path=/inventory/**
##        filters:
##          - RewritePath=/inventory/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,threaddump, metrics

eureka:
  client:
    service-url:
      defaultZone: https://${EUREKA_GATEWAY_URL:localhost}:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_URL:localhost}
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    non-secure-port-enabled: false   # Disable non-secure HTTP port
    secure-port-enabled: true        # Enable secure HTTPS port
    secure-port: ${server.port}

server:
  port: ${GATEWAY_API_PORT:7777}
  http2:
    enabled: true
  use-forwarded-headers: true
  ssl:
    enabled: true
    key-store: ${GATEWAY_KEY_STORE}
    key-store-password: ${GATEWAY_KEY_STORE_PASSWORD}
    key-alias: ${GATEWAY_ALIAS_NAME:gateway-app}
    key-store-type: PKCS12
    trust-store: ${GATEWAY_TRUST_STORE}
    trust-store-password: ${GATEWAY_TRUST_STORE_PASSWORD}
    trust-store-type: JKS
    client-auth: want
#    enabled-protocols: TLSv1.2,TLSv1.3
#    ciphers:ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_AES_128_GCM_SHA256

logging:
  file:
    name: logs/api-gateway.log
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.client.discovery: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
    io.github.resilience4j.circuitbreaker.internal: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
    org.springframework.data.redis: DEBUG
    javax.net.ssl: DEBUG