spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8281/realms/LiteMesh

server:
  port: 0
  ssl:
    enabled: true
    key-store: file:../../keys/client-keystore.jks
    key-store-password: 123456
    key-alias: client-app
    key-store-type: PKCS12
    trust-store: file:../../keys/client-truststore.jks
    trust-store-password: 123456
    trust-store-type: JKS
    client-auth: want

gateway:
  base-url: https://localhost:7777

logging:
  file:
    name: logs/product-service.log
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    non-secure-port-enabled: false   # Disable non-secure HTTP port
    secure-port-enabled: true        # Enable secure HTTPS port
    secure-port: ${server.port}