spring:
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8281/realms/LiteMesh
server:
  port: 0

logging:
  file:
    name: logs/inventory-service.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${instanceId:${random.value}}