#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: discovery-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: discovery-server
#  template:
#    metadata:
#      labels:
#        app: discovery-server
#    spec:
#      containers:
#        - name: discovery-service
#          image: discovery-service:latest
#          ports:
#            - containerPort: 8761
#          env:
#            - name: EUREKA_KEY_STORE
#              value: "/app/eureka-keystore.jks"
#            - name: EUREKA_KEY_STORE_PASSWORD
#              value: "123456"
#            - name: EUREKA_TRUST_STORE
#              value: "/app/eureka-truststore.jks"
#            - name: EUREKA_TRUST_STORE_PASSWORD
#              value: "123456"
#            - name: EUREKA_GATEWAY_URL
#              value: "discovery-service"
#            - name: EUREKA_ALIAS_NAME
#              value: "eureka-app-container"
#          volumeMounts:
#            - name: discovery-server
#              mountPath: "/app/discovery-server"
#            - name: keys
#              mountPath: "/app/keys"
#      volumes:
#        - name: discovery-server
#          hostPath:
#            path: discovery-server  # Change to your path
#        - name: keys
#          hostPath:
#            path: keys  # Change to your path
