## lite-gateway-ingress.yml
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: api-gateway-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#spec:
#  rules:
#    - host: api-gateway.example.com  # Replace with your own domain
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: api-gateway
#                port:
#                  number: 80
#  tls:
#    - hosts:
#        - api-gateway.example.com
#      secretName: api-gateway-tls  # Secret with TLS cert for HTTPS access
