## lite-gateway-deployment.yml
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: api-gateway
#  labels:
#    app: api-gateway
#spec:
#  replicas: 3  # Adjust the number of replicas here if needed
#  selector:
#    matchLabels:
#      app: api-gateway
#  template:
#    metadata:
#      labels:
#        app: api-gateway
#    spec:
#      containers:
#        - name: api-gateway
#          image: litemeshapp-api-gateway-service  # Replace with your actual image name
##          ports:
##            - containerPort: 0  # Internal port exposed by the api-gateway app
#          env:
#            - name: GATEWAY_TRUST_STORE
#              value: "/app/gateway-truststore.jks"
#            - name: GATEWAY_TRUST_STORE_PASSWORD
#              value: "123456"
#            - name: GATEWAY_KEY_STORE
#              value: "/app/gateway-keystore.jks"
#            - name: GATEWAY_KEY_STORE_PASSWORD
#              value: "123456"
#            - name: REDIS_GATEWAY_URL
#              value: "redis-service"
#            - name: MONGO_GATEWAY_URL
#              value: "mongodb-service"
#            - name: KEYCLOAK_GATEWAY_URL
#              value: "keycloak-service"
#            - name: KEYCLOAK_GATEWAY_PORT
#              value: "8080"
#            - name: EUREKA_GATEWAY_URL
#              value: "discovery-service"
